version: "3.8"
services:
  monolith_app:
    image: "monolith:latest"
    container_name: monolith
    ports:
      - "8080:8080" # host:container
    deploy: # configure the container's cpu and memory limits
      resources:
        limits: # limit to 2 CPUs and 512 MB
          cpus: "4.0"
          memory: 512M
        # reservations: # reserve 1 CPU and 256 MB
        #   cpus: "1.0"
        #   memory: 256M
    networks: # set the network to connect with other services and databases externally
      - postgres
    environment: # spring boot application.yml properties
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-skripsi:5432/monolith
      - SPRING_DATASOURCE_USERNAME=siplah
      - SPRING_DATASOURCE_PASSWORD=siplah
      - SERVER_TOMCAT_ACCEPT-COUNT=60
      - SERVER_TOMCAT_MAX-CONNECTIONS=60
      - SERVER_TOMCAT_THREADS_MAX=60

  postgres:
    image: "postgres:latest"
    container_name: postgres-skripsi
    environment:
      - POSTGRES_USER=siplah
      - POSTGRES_PASSWORD=siplah
    volumes:
      - db:/var/lib/postgresql_skripsi/data
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge
volumes:
  db:
    driver: local
