version: "3.8"
services:
  courses_federated:
    image: "course-federated:latest"
    container_name: course-federated
    ports:
      - "8086:8086"
    networks:
      - postgres
      - microservices
    deploy:
      resources:
        limits:
          cpus: "4.0"
          memory: 512M
    environment:
      - EXTERNAL_COURSE_URL=http://course-service:8082/api/course
      - EXTERNAL_CHAPTER_URL=http://course-service:8082/api/chapter
      - EXTERNAL_APPLICATION_URL=http://order-service:8083/api/job-application
      - EXTERNAL_VACANCY_URL=http://order-service:8083/api/job-vacancy
      - EXTERNAL_ORDER_URL=http://order-service:8083/api/order

  users_federated:
    image: "user-federated:latest"
    container_name: user-federated
    ports:
      - "8085:8085"
    networks:
      - postgres
      - microservices
    deploy:
      resources:
        limits:
          cpus: "4.0"
          memory: 512M
    environment:
      - EXTERNAL_USER_URL=http://user-service:8081/api/user
      - EXTERNAL_NOTIF_URL=http://notification-service:8084/api/notification

  apollo_gateway:
    image: "apollo-gateway:latest"
    container_name: apollo-gateway
    ports:
      - "4000:4000"
    networks:
      - postgres
      - microservices
    environment:
      - SERVER_PORT=4000
      - SERVICES_USERS_URL=http://user-federated:8085/graphql
      - SERVICES_COURSES_URL=http://course-federated:8086/graphql
    depends_on:
      - courses_federated
      - users_federated

networks:
  postgres:
    driver: bridge
  microservices:
    driver: bridge
# docker-compose -f docker-compose.federated.yml up -d
