server:
  port: 8090
spring:
  cloud:
    gateway:
      routes:
        - id: graphql
          uri: http://localhost:8080
          predicates:
            - Path=/graphql
          filters:
            - name: RequestRateLimiter
              args:
                # The redis-rate-limiter.replenishRate property defines how many requests per second to allow (without any dropped requests).
                # This is the rate at which the token bucket is filled.
                redis-rate-limiter.replenishRate: 60
                # The redis-rate-limiter.burstCapacity property is the maximum number of requests a user is allowed in a single second (without any dropped requests).
                # This is the number of tokens the token bucket can hold. Setting this value to zero blocks all requests.
                redis-rate-limiter.burstCapacity: 200
  redis:
    host: localhost
    port: 6379
