server:
  port: 8090
spring:
  cloud:
    gateway:
      routes:
        - id: graphql
          uri: http://localhost:8080
          predicates:
            - Path=/graphql
  redis:
    host: localhost
    port: 6379
